
import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') });

const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const majorClinics = [
    "R3 Stem Cell International",
    "Vivid Health",
    "BioXcellerator",
    "Cellular Performance Institute",
    "European Wellness Center",
    "Swiss Biological Medicine Center",
    "Hope4Cancer",
    "Panama Stem Cell Institute"
];

const medicalKeywords = [
    "regenerative protocols", "bio-restorative medicine", "cellular optimization",
    "integrative oncology", "metabolic therapy", "systemic rejuvenation"
];

const facilityKeywords = [
    "state-of-the-art laboratory", "boutique medical facility", "internationally accredited center",
    "exclusive wellness retreat", "advanced diagnostic suite"
];

function generateProfessionalDescription(clinicName: string, city: string | undefined) {
    const specializedTerm = medicalKeywords[Math.floor(Math.random() * medicalKeywords.length)];
    const facilityTerm = facilityKeywords[Math.floor(Math.random() * facilityKeywords.length)];
    const year = 2005 + Math.floor(Math.random() * 15);

    return `${clinicName} establishes itself as a premier destination for ${specializedTerm} in ${city || 'the region'}. Operating within a ${facilityTerm}, the team focuses on bridging the gap between conventional medical standards and cutting-edge longevity science.

**Clinical Excellence:**
Patients at ${clinicName} receive personalized care pathways designed to address the root causes of aging and chronic inflammation. By leveraging advanced diagnostics and ${specializedTerm}, the clinic ensures that every protocol is tailored to the unique biological needs of the individual.

**Why Choose ${clinicName}:**
*   **Expert Oversight**: Led by board-certified physicians specializing in integrative medicine.
*   **Comprehensive Care**: From initial consultation to post-treatment follow-up, the patient journey is managed with white-glove service.
*   **Safety & Compliance**: Adhering to strict international medical safety standards to ensure optimal outcomes.`;
}

async function updateAllClinics() {
    // Fetch clinics NOT in the major list
    const { data: clinics, error } = await supabase
        .from('clinics')
        .select('id, name, city_id, cities(name)')
        .not('name', 'in', `(${majorClinics.map(n => `"${n}"`).join(',')})`);

    if (error || !clinics) {
        console.error('Error fetching clinics:', error);
        return;
    }

    console.log(`Updating ${clinics.length} remaining clinics with professional content...`);

    for (const clinic of clinics) {
        const cityName = Array.isArray(clinic.cities) ? clinic.cities[0]?.name : (clinic.cities as any)?.name;
        const newDescription = generateProfessionalDescription(clinic.name, cityName);

        const { error: updateError } = await supabase
            .from('clinics')
            .update({
                description: newDescription,
                // Meta data should be auto-generated by the page component if missing, but we can set it too
                meta_description: newDescription.substring(0, 155) + "...",
                meta_title: `${clinic.name} in ${cityName || 'International'} | Verified Longevity Clinic`
            })
            .eq('id', clinic.id);

        if (updateError) console.error(`Failed ${clinic.name}: ${updateError.message}`);
        else console.log(`✅ Updated ${clinic.name}`);
    }
}

updateAllClinics();
